[package]
name = "hello"
version = "0.1.0"
authors = ["Sebastian Raaphorst <sraaphorst@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "1"
min-max = "0.1"
#num-traits = "0.2"
#num = "0.4"